version: 0.2

phases:
  install:
    runtime-versions:
      golang: latest
  build:
    commands:
      - go mod download
      - go build -o main
      - zip -g main.zip main
artifacts:
  files: main.zip

post_build:
  commands:
    - echo "Started"
    - aws lambda update-function-code --function-name go-lamda-sample --zip-file fileb://main.zip
    - echo "DONE!!"